# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checking_cheque.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63hecking_cheque.proto\x12\x0f\x63hecking_cheque\"5\n\x0e\x43hequeResponse\x12\x12\n\ncheque_ids\x18\x01 \x03(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x0c\x43heckRequest\x12\x15\n\rnational_code\x18\x01 \x01(\t2X\n\rChequeService\x12G\n\x05\x43heck\x12\x1d.checking_cheque.CheckRequest\x1a\x1f.checking_cheque.ChequeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checking_cheque_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHEQUERESPONSE']._serialized_start=42
  _globals['_CHEQUERESPONSE']._serialized_end=95
  _globals['_CHECKREQUEST']._serialized_start=97
  _globals['_CHECKREQUEST']._serialized_end=134
  _globals['_CHEQUESERVICE']._serialized_start=136
  _globals['_CHEQUESERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
