# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import checking_installment_pb2 as checking__installment__pb2


class CheckingInstallmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckInstallment = channel.unary_unary(
                '/checking_installment.CheckingInstallmentService/CheckInstallment',
                request_serializer=checking__installment__pb2.CheckInstallmentRequest.SerializeToString,
                response_deserializer=checking__installment__pb2.CheckInstallmentResponse.FromString,
                )


class CheckingInstallmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckInstallment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckingInstallmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckInstallment': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckInstallment,
                    request_deserializer=checking__installment__pb2.CheckInstallmentRequest.FromString,
                    response_serializer=checking__installment__pb2.CheckInstallmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checking_installment.CheckingInstallmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CheckingInstallmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckInstallment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checking_installment.CheckingInstallmentService/CheckInstallment',
            checking__installment__pb2.CheckInstallmentRequest.SerializeToString,
            checking__installment__pb2.CheckInstallmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
