# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checking_installment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63hecking_installment.proto\x12\x14\x63hecking_installment\"0\n\x17\x43heckInstallmentRequest\x12\x15\n\rnational_code\x18\x01 \x01(\t\"8\n\x18\x43heckInstallmentResponse\x12\x0b\n\x03ids\x18\x01 \x03(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8f\x01\n\x1a\x43heckingInstallmentService\x12q\n\x10\x43heckInstallment\x12-.checking_installment.CheckInstallmentRequest\x1a..checking_installment.CheckInstallmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checking_installment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKINSTALLMENTREQUEST']._serialized_start=52
  _globals['_CHECKINSTALLMENTREQUEST']._serialized_end=100
  _globals['_CHECKINSTALLMENTRESPONSE']._serialized_start=102
  _globals['_CHECKINSTALLMENTRESPONSE']._serialized_end=158
  _globals['_CHECKINGINSTALLMENTSERVICE']._serialized_start=161
  _globals['_CHECKINGINSTALLMENTSERVICE']._serialized_end=304
# @@protoc_insertion_point(module_scope)
