# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the directory containing your_server_file.py into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir grpcio grpcio-tools python-dotenv psycopg2-binary

# Make port 50051 available to the world outside this container
EXPOSE 50051

# Define environment variable
ENV PYTHONUNBUFFERED=1

# Run your_server_file.py when the container launches
CMD ["python", "cheque_server.py"]
